[package]
name = "Rust-Project"
version = "0.1.0"
edition = "2024"

[dependencies]
borsh = { version = "1.5.7", features = ["derive"] }
rand = "0.9.2"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
serde_yaml = "0.9.34"
